Redefinição de Senha
aLiviaMs/orion-bootcamp-back-alpha-orionis pull request #10
Opened 2023-10-28 05:12 UTC by gurgelff

Funções testadas e aptas para a apresentação.

- Geração e validação de Reset Token
- Envio de email está funcionando como previsto.
- Tratamento de dados incorretos e erros.
- Integrado com o Frontend
- Altamente documentado

OBS: Necessita das credenciais de configuração do e-mail para funcionar apropriadamente, que não foi commitado por questões de segurança.

2023-10-28 14:51 UTC, nr-elian requested changes

2023-10-30 21:40 UTC, gurgelff commented on README.md
> +Já para testar a seção de _Esqueci a Senha_, basta enviar uma requisição POST para /forgot-password com o e-mail do usuário:
Sim, concordo.
A partir deste ponto, o leitor já tem noção de como usar o Swagger, então ele já pode (e deve) fazer os testes por lá.

2023-10-30 21:45 UTC, gurgelff commented on src/controller/DashboardController.ts
> +      console.log(_err);
Sim, faz parte do debug e também remove as mensagens de alerta de _unused variable_.

Tudo bem se ignorar esses warnings?

2023-10-30 22:41 UTC, gurgelff commented on src/controller/HomeController.ts
Removi o Home e criei um Controller para o / que retorna a documentação da API em json.

2023-10-30 22:45 UTC, gurgelff commented
Alterações feitas:
- Remove endpoints desnecessário do README
- Remove HomeController sem uso
- Remove console.log's
- Cria nova migration para o novo usuário

2023-11-06 19:51 UTC, nr-elian approved these changes

2023-11-06 19:52 UTC, merged