feat: add middleware to fetch mars weather
aLiviaMs/orion-bootcamp-back-alpha-orionis pull request #11
Opened 2023-10-31 18:39 UTC by tiburciohugo

Implementação de um middleware com um método auxiliar para buscar os dados meteorológios de Marte. O método busca as 14 últimas medições realizadas e retorna uma lista com os objetos contendo o sol, a data e as temperaturas mínima e máxima.

2023-10-31 18:40 UTC, tiburciohugo commented
![](https://github.trello.services/images/mini-trello-icon.png) [[Squad Alpha Orionis] Criar um middleware que obtém dados da NASA](https://trello.com/c/50A5WKzK/377-squad-alpha-orionis-criar-um-middleware-que-obt%C3%A9m-dados-da-nasa)

2023-10-31 20:10 UTC, nr-elian requested changes

2023-10-31 20:10 UTC, nr-elian commented on src/middleware/getWeatherData.ts
> +    await getWeather(url);
Nunca vai cair no catch, já que na outra função também tem um try catch que retorna array vazio

2023-10-31 20:10 UTC, nr-elian commented on src/utils/getWeather.ts
> +    console.error('Erro ao buscar os dados meteorológicos:', error);
console.log não é tratamento de erro é preciso tratar esse catch para responder adequadamente para o front no endpoint depois, isso gera uma falsa sensação de funcionamento e mascara possiveis erros na api

2023-10-31 22:45 UTC, tiburciohugo commented
Removi o tratamento de erro e mudei tudo pro inglês.

2023-11-01 11:59 UTC, nr-elian approved these changes

2023-11-01 11:59 UTC, merged