Fix: Fahrenheit Variation
aLiviaMs/orion-bootcamp-back-alpha-orionis pull request #29
Opened 2023-11-16 19:23 UTC by gurgelff

Conserta os valores do Fahrenheit, que estavam retornando sempre Neutral, agora seguindo o mesmo esquema do Celsius, retornando corretamente Higher ou Lower quando se aplica (testado via Swagger).

2023-11-16 21:54 UTC, nr-elian requested changes

2023-11-16 21:54 UTC, nr-elian commented on src/utils/weather.ts
> +      index === 0 ? celsiusMinVariation : Variation.NEUTRAL;
porque a variável que chama: fahrenheitMinVariation retorna celsiusMinVariation?

2023-11-17 00:01 UTC, gurgelff commented on src/utils/weather.ts
> +      index === 0 ? celsiusMinVariation : Variation.NEUTRAL;
Foi desatenção de minha parte. Irei renomear a variável de referência para um nome abrangente: temperatureMinVariation.

2023-11-18 16:51 UTC, nr-elian approved these changes

2023-11-18 16:52 UTC, merged