Validação de Força de Senha
aLiviaMs/orion-bootcamp-back-alpha-orionis pull request #7
Opened 2023-10-24 05:34 UTC by gurgelff

Criei um Middleware que valida a força da senha.

Adicionei ao Readme instruções de como inserir um usuário exemplo no banco de dados a fim de testar os middlewares usando um db real.

2023-10-27 14:00 UTC, nr-elian requested changes

2023-10-27 14:00 UTC, nr-elian commented on README.md
> +Insira o usuário de teste:
@tiburciohugo resolveu isso com migration, agora quando a api roda pela primeira vez ele cria o usuário no banco de dados

2023-10-27 14:00 UTC, nr-elian commented on README.md
> +  "password": "Senh@Fort3",
credencial nem de exemplo em documentação ou código sempre deixar a string vazia

2023-10-27 14:00 UTC, nr-elian commented on src/controller/AuthController.ts
> +   *                 example: "Senh@Fort3"
sem credencial, mesmo que não seja verdadeira no swagger

2023-10-27 14:00 UTC, nr-elian commented on src/routes.ts
> +router.post(
Faz sentido validar a força da senha no login?
O login deve verificar se o usuário e senha existem na base, isso pode gerar um "bug" do ponto de vista do usuário que ja existe no projeto, essa é uma regra importante para o cadastro de nova senha.

2023-10-27 19:51 UTC, gurgelff commented on src/routes.ts
> +router.post(
Eu concordo com essa abordagem _godfather_, ou seja, os antigos usuários não devem ser prejudicados.
Ocorre que no documento está disposto o uso dessa validação durante o _login_ (a tela de cadastro não existe).

Eu irei realizar as alterações, deixando o middleware de validação da senha somente para o reset password.
Irei tomar nota e mencionar o caso no refinamento técnico e na DEMO de hoje.

2023-10-28 04:04 UTC, gurgelff commented
Mudanças aplicadas.
Conflito no routes.ts resolvido.

2023-10-28 13:06 UTC, nr-elian requested changes

2023-10-28 13:56 UTC, gurgelff commented on src/config/database.ts
> -  synchronize: true,
De fato, eu acabei revertendo diversas mudanças nesse processo. Vou ajeitar isso.

2023-10-28 15:36 UTC, gurgelff commented
Sincronizei local e resolvi os conflitos.
Subi o arquivo de rotas (conflitante).

Removi a importação desnecessária para esta task.

2023-10-31 20:03 UTC, nr-elian requested changes

2023-10-31 20:03 UTC, nr-elian commented on src/middleware/validateEmail.ts
Segue removendo arquivos em uso, essa branch não está nem rodando

<img width="631" alt="image" src="https://github.com/aLiviaMs/orion-bootcamp-back-alpha-orionis/assets/137924628/96244d05-006e-4a5a-a307-0d2be8decf43">

2023-11-01 18:32 UTC, gurgelff commented on src/middleware/validateEmail.ts
Ok, agora este PR está apenas alterando (criando) um único arquivo.

2023-11-06 19:09 UTC, nr-elian approved these changes

2023-11-06 19:10 UTC, merged