Feature/email service
aLiviaMs/orion-bootcamp-back-alpha-orionis pull request #8
Opened 2023-10-26 18:02 UTC by tiburciohugo

Criação de um método para enviar emails a partir do SMTP do Gmail. OBS: O corpo do email não é difinitivo e apenas para teste.

2023-10-26 18:03 UTC, tiburciohugo commented
![](https://github.trello.services/images/mini-trello-icon.png) [[Squad Alpha Orionis]: Validação de e-mails](https://trello.com/c/A4TjoH9b/200-squad-alpha-orionis-valida%C3%A7%C3%A3o-de-e-mails)

2023-10-27 14:03 UTC, nr-elian requested changes

2023-10-27 14:03 UTC, nr-elian commented on src/utils/sendEmail.ts
> +    pass: 'rqayhdwhbmozbhpf',
Tem que vir das ENVS o user e o pass

2023-10-27 14:07 UTC, tiburciohugo commented on src/utils/sendEmail.ts
> +    pass: 'rqayhdwhbmozbhpf',
Feito.

2023-10-27 15:38 UTC, nr-elian approved these changes

2023-10-27 15:53 UTC, merged